"use client";

import * as React from "react";
import Link from "next/link";
import { BookOpenCheck, ChevronDown, Download, ExternalLink, FileCheck2, FileText, LoaderCircle, Shapes } from "lucide-react";
import { downloadLessonKitMaterial, fetchLessonKit } from "@/lib/lesson-kit-api";
import { lessonKitMaterials, type LessonKit, type LessonKitMaterialType } from "@/lib/lesson-kit";
import { lessonKitMaterialEditorHref } from "@/lib/kit-material-editor";

const icons:Record<LessonKitMaterialType,typeof FileText>={LESSON_PLAN:BookOpenCheck,STUDENT_ACTIVITY:Shapes,TEACHER_ANSWER_KEY:FileCheck2,ASSESSMENT:FileText,PEDAGOGICAL_EVIDENCE:FileText,INCLUSIVE_ADAPTATIONS:FileText};

export function ClassroomKitDropdown({kitId,documentId}:{kitId:number;documentId:number}){
  const[expanded,setExpanded]=React.useState(false);const[kit,setKit]=React.useState<LessonKit|null>(null);const[loading,setLoading]=React.useState(false);const[error,setError]=React.useState<string|null>(null);const[downloading,setDownloading]=React.useState<LessonKitMaterialType|null>(null);
  async function toggle(){const next=!expanded;setExpanded(next);if(next&&!kit&&!loading){setLoading(true);setError(null);try{setKit(await fetchLessonKit(kitId));}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível carregar o kit.");}finally{setLoading(false)}}}
  async function download(type:LessonKitMaterialType,label:string){setDownloading(type);try{await downloadLessonKitMaterial(kitId,type,`${kit?.topic??"Kit de aula"} - ${label}`);}finally{setDownloading(null)}}
  const materialHref=(type:LessonKitMaterialType)=>lessonKitMaterialEditorHref(documentId,kitId,type);
  return <div className="w-full max-w-2xl overflow-hidden rounded-2xl border border-indigo-100 bg-indigo-50/40 shadow-sm"><button type="button" onClick={toggle} aria-expanded={expanded} aria-controls={`classroom-kit-${kitId}`} className="flex min-h-12 w-full cursor-pointer items-center justify-between gap-4 px-4 py-3 text-left transition-colors hover:bg-indigo-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><span className="flex items-center gap-3"><span className="rounded-xl bg-indigo-600 p-2 text-white"><BookOpenCheck className="h-4 w-4" aria-hidden="true"/></span><span><strong className="block text-sm text-slate-900">Kit de aula completo</strong><span className="text-xs text-slate-600">Plano + 5 materiais pedagógicos</span></span></span><ChevronDown className={`h-5 w-5 text-indigo-600 transition-transform motion-reduce:transition-none ${expanded?"rotate-180":""}`} aria-hidden="true"/></button>{expanded&&<div id={`classroom-kit-${kitId}`} className="border-t border-indigo-100 bg-white p-3"><p className="px-2 pb-2 text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Materiais do kit</p>{loading&&<div className="flex min-h-14 items-center gap-2 px-2 text-sm text-slate-600" aria-live="polite"><LoaderCircle className="h-4 w-4 animate-spin"/> Carregando materiais…</div>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{kit&&<ul className="space-y-1">{lessonKitMaterials.map(definition=>{const material=kit.materials.find(item=>item.type===definition.type);const Icon=icons[definition.type];const ready=material?.status==="READY";return <li key={definition.type} className="flex flex-col gap-2 rounded-xl px-3 py-2.5 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><span className="flex min-w-0 items-center gap-3"><Icon className="h-4 w-4 shrink-0 text-indigo-600" aria-hidden="true"/><span><span className="block text-sm font-semibold text-slate-800">{definition.label}</span><span className="text-xs text-slate-500">{ready?"Pronto para usar":material?.status==="FAILED"?"Falha na geração":"Em preparação"}</span></span></span><span className="flex gap-2 pl-7 sm:pl-0"><Link href={materialHref(definition.type)} className="inline-flex min-h-11 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700 hover:bg-white focus-visible:ring-2 focus-visible:ring-indigo-500"><ExternalLink className="h-3.5 w-3.5"/> Abrir</Link><button disabled={!ready||downloading===definition.type} onClick={()=>download(definition.type,definition.label)} aria-label={`Baixar ${definition.label}`} className="inline-flex min-h-11 items-center gap-1.5 rounded-lg border border-indigo-200 px-3 text-xs font-semibold text-indigo-700 hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-3.5 w-3.5"/>{downloading===definition.type?"Baixando…":"Baixar"}</button></span></li>})}</ul>}</div>}</div>;
}
