import { API_BASE_URL, ApiError, getToken, invalidateCache, request } from "@/lib/api";
import type { LessonKit,LessonKitMaterial,LessonKitMaterialType } from "@/lib/lesson-kit";
export interface ActivityGenerationSettings { activityCount:number; exercisesPerActivity:number; format:string; purpose:string; difficulty:string; modality:string }
export async function createLessonKit(documentId:number){const kit=await request<LessonKit>(`/lesson-kits/from-plan/${documentId}`,{method:"POST"});invalidateCache();return kit;}
export function fetchLessonKit(id:number|string){return request<LessonKit>(`/lesson-kits/${id}`);}
export function updateLessonKitMaterial(kitId:number,type:LessonKitMaterialType,content:string,version:number){return request<LessonKitMaterial>(`/lesson-kits/${kitId}/materials/${type}`,{method:"PUT",body:JSON.stringify({content,version})});}
export function regenerateLessonKitMaterial(kitId:number,type:LessonKitMaterialType,settings?:ActivityGenerationSettings){return request<LessonKitMaterial>(`/lesson-kits/${kitId}/materials/${type}/regenerate`,{method:"POST",body:settings?JSON.stringify(settings):undefined});}
export async function fetchLessonKitMaterialPdfUrl(kitId:number,type:LessonKitMaterialType){const headers=new Headers();const token=getToken();if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE_URL}/lesson-kits/${kitId}/materials/${type}/export.pdf`,{headers});if(!response.ok)throw new ApiError("Não foi possível gerar o PDF para impressão.",response.status);return URL.createObjectURL(await response.blob());}
export async function downloadLessonKitMaterial(kitId:number,type:LessonKitMaterialType,title:string){const headers=new Headers();const token=getToken();if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${API_BASE_URL}/lesson-kits/${kitId}/materials/${type}/export.docx`,{headers});if(!response.ok)throw new ApiError("Não foi possível exportar o material.",response.status);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${title.replace(/[^\p{L}\p{N}\s-]/gu,"").trim()||"material-do-kit"}.docx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
